name: Deploy Next.js site to Pages

on:
  push:
    branches: [ main ]

env:
  # Pokud je tvá aplikace v podadresáři, změň '.' na 'frontend' nebo jiný path
  PROJECT_DIR: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (supports yarn or npm)
        run: |
          cd "$PROJECT_DIR"
          if [ -f "yarn.lock" ]; then
            echo "Using yarn"
            yarn install --frozen-lockfile || yarn install
          elif [ -f "package-lock.json" ]; then
            echo "Using npm (ci)"
            npm ci
          elif [ -f "package.json" ]; then
            echo "Using npm (install)"
            npm install
          else
            echo "No package.json or lockfile found in $PROJECT_DIR" && exit 1
          fi

      - name: Build
        run: |
          cd "$PROJECT_DIR"
          npm run build || yarn build

      - name: Export static site (if using next export)
        run: |
          cd "$PROJECT_DIR"
          npm run export || yarn export || true

      - name: Verify output directory
        run: |
          if [ -d "$PROJECT_DIR/out" ]; then
            echo "Found static export at $PROJECT_DIR/out"
          else
            echo "No $PROJECT_DIR/out directory found."
            echo "If you use `next export`, ensure your build creates an 'out' folder."
            exit 1
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        # Aktualizováno na verzi, která by neměla záviset na upload-artifact@v3
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.PROJECT_DIR }}/out

      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
        
